/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class per_jianfei_myjniapplication_MyJNI */

#ifndef _Included_per_jianfei_myjniapplication_MyJNI
#define _Included_per_jianfei_myjniapplication_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     per_jianfei_myjniapplication_MyJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_per_jianfei_myjniapplication_MyJNI_sayHello
  (JNIEnv *env, jclass jobj) {
    return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");
  }

#ifdef __cplusplus
}
#endif
#endif
